### ISSUE TITLE
Analisi Qualità del codice con Analisi Statica

### ISSUE THREAD

**Issue by giuseppe-santoro** [apuliasoft/design-angular-kit#10]
Configurare uno strumento in grado di eseguire automaticamente l'analisi statica del codice TypeScript secondo le specifiche comunemente usate in ambito TypeScript su progetti OpenSource.

Valutare [Code Climate](https://codeclimate.com/)

**Comment by ciccio86** [comment]
A questo [link](https://www.netguru.co/blog/comparison-automated-code-review-tools-codebeat-codacy-codeclimate-scrutinizer) è possibile trovare una comparazione di tool.

**Comment by ciccio86** [comment]
E' stato integrato Code Climate.
